/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthQueueRouteImport } from './routes/_auth/queue'
import { Route as AuthServicesIndexRouteImport } from './routes/_auth/services/index'
import { Route as AuthServicesNewRouteImport } from './routes/_auth/services/new'
import { Route as AuthServicesIdEditRouteImport } from './routes/_auth/services/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthQueueRoute = AuthQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthRoute,
} as any)
const AuthServicesIndexRoute = AuthServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthServicesNewRoute = AuthServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthServicesIdEditRoute = AuthServicesIdEditRouteImport.update({
  id: '/services/$id/edit',
  path: '/services/$id/edit',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/queue': typeof AuthQueueRoute
  '/services/new': typeof AuthServicesNewRoute
  '/services/': typeof AuthServicesIndexRoute
  '/services/$id/edit': typeof AuthServicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/queue': typeof AuthQueueRoute
  '/services/new': typeof AuthServicesNewRoute
  '/services': typeof AuthServicesIndexRoute
  '/services/$id/edit': typeof AuthServicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/queue': typeof AuthQueueRoute
  '/_auth/services/new': typeof AuthServicesNewRoute
  '/_auth/services/': typeof AuthServicesIndexRoute
  '/_auth/services/$id/edit': typeof AuthServicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/queue'
    | '/services/new'
    | '/services/'
    | '/services/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/queue'
    | '/services/new'
    | '/services'
    | '/services/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/queue'
    | '/_auth/services/new'
    | '/_auth/services/'
    | '/_auth/services/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/queue': {
      id: '/_auth/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthQueueRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/services/': {
      id: '/_auth/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthServicesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/services/new': {
      id: '/_auth/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AuthServicesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/services/$id/edit': {
      id: '/_auth/services/$id/edit'
      path: '/services/$id/edit'
      fullPath: '/services/$id/edit'
      preLoaderRoute: typeof AuthServicesIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthQueueRoute: typeof AuthQueueRoute
  AuthServicesNewRoute: typeof AuthServicesNewRoute
  AuthServicesIndexRoute: typeof AuthServicesIndexRoute
  AuthServicesIdEditRoute: typeof AuthServicesIdEditRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthQueueRoute: AuthQueueRoute,
  AuthServicesNewRoute: AuthServicesNewRoute,
  AuthServicesIndexRoute: AuthServicesIndexRoute,
  AuthServicesIdEditRoute: AuthServicesIdEditRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
